-- Migration 009: lesson_content table + path intro/closing columns
-- Pre-seeded lesson content for Belajar Al-Qur'an feature (no runtime GPT)

-- New columns on learning_paths
ALTER TABLE learning_paths ADD COLUMN IF NOT EXISTS path_intro TEXT;
ALTER TABLE learning_paths ADD COLUMN IF NOT EXISTS path_closing TEXT;

-- New table: lesson_content (one row per lesson, pre-generated by seed script)
CREATE TABLE IF NOT EXISTS lesson_content (
  lesson_id TEXT PRIMARY KEY REFERENCES lessons(id) ON DELETE CASCADE,
  insight JSONB NOT NULL,
  kata_kunci JSONB,
  doa JSONB,
  renungan JSONB NOT NULL,
  generated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE lesson_content ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read lesson_content" ON lesson_content FOR SELECT USING (true);
